version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: shg-api-dev
    restart: unless-stopped
    pull_policy: build
    env_file:
      - .env.development
    networks:
      - shg-net
    expose:
      - "8080"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: npx drizzle-kit migrate --config=drizzle.config.prod.ts
    env_file:
      - .env.development
networks:
  shg-net:
    external: true