version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: shg-api-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.development

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: npx drizzle-kit migrate --config=drizzle.config.prod.ts
    env_file:
      - .env.development